[package]
name = "yukin"
version = "0.1.0"
description = "agent."
authors = ["leviegu <leviegu@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "yukin_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
sqlx = { version = "0.9.0", default-features = false, features = [
  "runtime-tokio",
  "sqlite",
  "macros",
  "migrate",
  "chrono",
  "uuid",
] }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.24.0", features = ["v7"] }
thiserror = "2.0.20"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
keyring = { version = "4.1.6", features = [
  "apple-native-keyring-store",
  "windows-native-keyring-store",
] }
minidumper-child = "0.3.0"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
eventsource-stream = "0.2.3"
futures-util = "0.3.34"
chrono = "0.4"
dirs = "6"
tokio = { version = "1", features = ["fs", "io-util", "macros", "sync", "time"] }
sha2 = "0.10"
hex = "0.4"
tauri-plugin-dialog = "2"
zip = { version = "5", default-features = false, features = ["deflate"] }
