/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as InitializeRouteImport } from './routes/initialize'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettingsMcpServersRouteImport } from './routes/settings.mcp-servers'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsSkillsRouteImport } from './routes/settings.skills'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const InitializeRoute = InitializeRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof ChatRoute
  '/initialize': typeof InitializeRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/initialize': typeof InitializeRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/chat': typeof ChatRoute
  '/initialize': typeof InitializeRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/initialize'
    | '/settings'
    | '/settings/mcp-servers'
    | '/settings/providers'
    | '/settings/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/initialize'
    | '/settings'
    | '/settings/mcp-servers'
    | '/settings/providers'
    | '/settings/skills'
  id:
    | '__root__'
    | '/chat'
    | '/initialize'
    | '/settings'
    | '/settings/mcp-servers'
    | '/settings/providers'
    | '/settings/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRoute
  InitializeRoute: typeof InitializeRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialize': {
      id: '/initialize'
      path: '/initialize'
      fullPath: '/initialize'
      preLoaderRoute: typeof InitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp-servers': {
      id: '/settings/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRoute,
  InitializeRoute: InitializeRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
